'use client';
import { useOperationsStore } from '@/operations/useOperationsStore';
export function BatchDetail({ batchId }: { batchId: string }) {
  const { dataset, sessionId } = useOperationsStore();
  const session = dataset.sessions.find((item) => item.id === sessionId)!;
  const batch = dataset.batches.find((item) => item.id === batchId && item.tenantId === session.tenantId);
  if (!batch) return <div className="ops-empty"><h2>Batch unavailable</h2><p>The batch does not exist in the active tenant or your role cannot access it.</p></div>;
  const assets = dataset.assets.filter((item) => item.batchId === batch.id);
  const attestation = dataset.attestations.find((item) => item.batchId === batch.id);
  return <div className="ops-dashboard-grid"><article className="ops-panel ops-wide"><header><div><span>Batch record</span><h2>{batch.reference}</h2></div><em data-state={batch.status}>{batch.status}</em></header><dl className="ops-detail-grid"><div><dt>Name</dt><dd>{batch.name}</dd></div><div><dt>Location</dt><dd>{dataset.locations.find((item) => item.id === batch.locationId)?.name}</dd></div><div><dt>Units</dt><dd>{assets.length}</dd></div><div><dt>Version</dt><dd>{batch.version}</dd></div></dl></article><article className="ops-panel"><span className="ops-kicker">Attestation</span><h2>{attestation ? `Version ${attestation.version}` : 'Not signed'}</h2><p>{attestation?.declaration ?? 'An authorized attestor must sign before submission.'}</p></article><article className="ops-panel"><span className="ops-kicker">Validation</span><h2>{batch.validationErrors.length} issues</h2><ul className="ops-issue-list">{batch.validationErrors.slice(0, 12).map((issue, index) => <li key={`${issue.code}-${index}`} data-severity={issue.severity}><strong>{issue.code}</strong>{issue.message}</li>)}</ul></article><article className="ops-panel ops-wide"><header><div><span>Unit inventory</span><h2>Individually identified assets</h2></div></header><div className="ops-table"><div className="ops-table-head"><span>Serial</span><span>Status</span><span>Weight</span><span>Evidence</span></div>{assets.map((asset) => <div key={asset.id}><span><strong>{asset.serial}</strong><small>{asset.id}</small></span><em data-state={asset.status}>{asset.status}</em><span>{asset.measurements.weightCarats ?? '—'} ct</span><span>{asset.evidenceIds.length}</span></div>)}</div></article></div>;
}
