'use client';

import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react';
import { authorityFetch } from '@/operations/auth';

type Row = Record<string, unknown> & { id?: string };
type Snapshot = {
  commercialAccounts: Row[];
  commercialOpportunities: Row[];
  commercialContracts: Row[];
  contractVersions: Row[];
  entitlements: Row[];
  provisioningEvents: Row[];
  invoices: Row[];
  payments: Row[];
  refunds: Row[];
  billingReconciliations: Row[];
  supportCases: Row[];
  supportEvents: Row[];
  commercialRemedies: Row[];
  preferences: Row[];
};
type Envelope<T> = { data?: T; error?: { code?: string; message?: string } };

async function request<T>(path: string, init?: RequestInit): Promise<T> {
  const response = await authorityFetch(path, { cache: 'no-store', ...init, headers: { 'content-type': 'application/json', ...(init?.headers ?? {}) } });
  const body = await response.json().catch(() => ({})) as Envelope<T>;
  if (!response.ok || !body.data) throw new Error(body.error?.message ?? body.error?.code ?? `COMMERCIAL_AUTHORITY_FAILED_${response.status}`);
  return body.data;
}
function split(value: FormDataEntryValue | null) { return String(value ?? '').split(',').map((item) => item.trim()).filter(Boolean); }
function iso(value: FormDataEntryValue | null) { const raw=String(value ?? '').trim(); return raw ? new Date(raw).toISOString() : ''; }
function id(row: Row) { return String(row.id ?? ''); }
function label(row: Row, ...keys: string[]) { for (const key of keys) if (row[key] != null) return String(row[key]); return id(row) || 'record'; }
function num(value: FormDataEntryValue | null) { return Number(String(value ?? '0')); }

export function CommercialAuthorityPanel() {
  const [snapshot,setSnapshot]=useState<Snapshot|null>(null);
  const [message,setMessage]=useState('Loading commercial authority…');
  const [busy,setBusy]=useState(false);
  const load=useCallback(async()=>{ try { setSnapshot(await request<Snapshot>('/api/v1/authority/operational-controls')); setMessage('Commercial authority loaded.'); } catch(error){ setMessage(error instanceof Error?error.message:'Commercial authority unavailable.'); } },[]);
  useEffect(()=>{void load();},[load]);
  const totals=useMemo(()=>snapshot?{
    accounts:snapshot.commercialAccounts.length,
    activeAccounts:snapshot.commercialAccounts.filter((row)=>row.lifecycleState==='active').length,
    activeEntitlements:snapshot.entitlements.filter((row)=>row.status==='active').length,
    outstandingInvoices:snapshot.invoices.filter((row)=>!['paid','void'].includes(String(row.state))).length,
    openSupport:snapshot.supportCases.filter((row)=>!['resolved','closed'].includes(String(row.state))).length,
    blockedReconciliations:snapshot.billingReconciliations.filter((row)=>row.state!=='pass').length,
  }:null,[snapshot]);

  async function commit(path:string,payload:Record<string,unknown>,form?:HTMLFormElement){
    try{setBusy(true);setMessage('Committing commercial authority operation…');await request(path,{method:'POST',body:JSON.stringify(payload)});form?.reset();await load();setMessage('Commercial authority operation committed and audit-bound.');}
    catch(error){setMessage(error instanceof Error?error.message:'Commercial authority operation failed closed.');}
    finally{setBusy(false);}
  }
  async function createAccount(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=event.currentTarget,d=new FormData(f);await commit('/api/v1/authority/operational-controls/commercial-accounts',{accountName:d.get('accountName'),externalCrmId:d.get('externalCrmId')||null,lifecycleState:'prospect',contractState:'missing',provisioningState:'pending',billingProfileVerified:d.get('billingProfileVerified')==='on',tenantIsolationVerified:d.get('tenantIsolationVerified')==='on'},f);}
  async function createOpportunity(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=event.currentTarget,d=new FormData(f);await commit('/api/v1/authority/operational-controls/commercial-opportunities',{accountId:d.get('accountId')||null,externalCrmId:d.get('externalCrmId')||null,stage:d.get('stage'),productCodes:split(d.get('productCodes')),estimatedValue:num(d.get('estimatedValue')),currency:d.get('currency'),ownerIdentity:d.get('ownerIdentity'),nextAction:d.get('nextAction')||null,expectedCloseAt:iso(d.get('expectedCloseAt'))||null},f);}
  async function createContract(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=event.currentTarget,d=new FormData(f);await commit('/api/v1/authority/commercial/contracts',{accountId:d.get('accountId'),status:d.get('status'),effectiveAt:iso(d.get('effectiveAt')),expiresAt:iso(d.get('expiresAt'))||null,documentDigest:d.get('documentDigest'),approverIdentities:split(d.get('approvers')),approvalSignatures:split(d.get('signatures')),productCodes:split(d.get('productCodes')),jurisdiction:d.get('jurisdiction'),policyVersion:d.get('policyVersion')},f);}
  async function activateAccount(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=event.currentTarget,d=new FormData(f),accountId=String(d.get('accountId')??'');await commit(`/api/v1/authority/commercial/accounts/${encodeURIComponent(accountId)}/activate`,{contractId:d.get('contractId'),entitlements:split(d.get('entitlements')),provisioningReceiptId:d.get('provisioningReceiptId'),tenantIsolationVerified:d.get('tenantIsolationVerified')==='on',billingProfileVerified:d.get('billingProfileVerified')==='on',evidence:{reference:d.get('evidenceReference')}},f);}
  async function createInvoice(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=event.currentTarget,d=new FormData(f),quantity=num(d.get('quantity')),unitAmount=num(d.get('unitAmount')),taxAmount=num(d.get('taxAmount')),totalAmount=Number((quantity*unitAmount+taxAmount).toFixed(2));await commit('/api/v1/authority/commercial/invoices',{accountId:d.get('accountId'),contractId:d.get('contractId'),currency:d.get('currency'),lines:[{code:d.get('lineCode'),quantity,unitAmount}],taxAmount,totalAmount,state:'issued',dueAt:iso(d.get('dueAt')),issuedAt:new Date().toISOString()},f);}
  async function recordPayment(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=event.currentTarget,d=new FormData(f),invoiceId=String(d.get('invoiceId')??'');await commit(`/api/v1/authority/commercial/invoices/${encodeURIComponent(invoiceId)}/payments`,{amount:num(d.get('amount')),currency:d.get('currency'),providerReference:d.get('providerReference'),idempotencyKey:d.get('idempotencyKey')},f);}
  async function authorizeRefund(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=event.currentTarget,d=new FormData(f),paymentId=String(d.get('paymentId')??'');await commit(`/api/v1/authority/commercial/payments/${encodeURIComponent(paymentId)}/refunds`,{amount:num(d.get('amount')),reason:d.get('reason'),approverIdentities:split(d.get('approvers')),approvalSignatures:split(d.get('signatures')),authorizationReceiptId:d.get('authorizationReceiptId')},f);}
  async function createSupport(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=event.currentTarget,d=new FormData(f);await commit('/api/v1/authority/operational-controls/support-cases',{caseType:d.get('caseType'),severity:d.get('severity'),state:'open',customerImpact:d.get('customerImpact')||null,credentialImpact:d.get('credentialImpact')||null,slaDueAt:iso(d.get('slaDueAt')),escalationPath:split(d.get('escalationPath')),evidenceIds:split(d.get('evidenceIds'))},f);}
  async function transitionSupport(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=event.currentTarget,d=new FormData(f),caseId=String(d.get('caseId')??'');await commit(`/api/v1/authority/commercial/support/${encodeURIComponent(caseId)}/transition`,{toState:d.get('toState'),evidence:{reference:d.get('evidenceReference')}},f);}
  async function remedy(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=event.currentTarget,d=new FormData(f);await commit('/api/v1/authority/commercial/remedies',{supportCaseId:d.get('supportCaseId'),refundId:d.get('refundId')||null,remedyType:d.get('remedyType'),financialState:d.get('financialState'),credentialAction:d.get('credentialAction'),credentialActionReason:d.get('credentialActionReason'),dualControlReceiptIds:split(d.get('dualControlReceiptIds')),evidence:{reference:d.get('evidenceReference')}},f);}
  async function preference(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=event.currentTarget,d=new FormData(f);await commit('/api/v1/authority/operational-controls/commercial-preferences',{subjectReference:d.get('subjectReference'),jurisdiction:d.get('jurisdiction'),purpose:d.get('purpose'),channel:d.get('channel'),granted:d.get('granted')==='on',policyVersion:d.get('policyVersion'),evidenceDigest:d.get('evidenceDigest'),supersedesId:d.get('supersedesId')||null,withdrawnAt:d.get('withdrawn')==='on'?new Date().toISOString():null},f);}
  async function reconciliation(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=event.currentTarget,d=new FormData(f);await commit('/api/v1/authority/commercial/reconciliations',{windowStart:iso(d.get('windowStart')),windowEnd:iso(d.get('windowEnd')),invoiceTotal:num(d.get('invoiceTotal')),paymentTotal:num(d.get('paymentTotal')),refundTotal:num(d.get('refundTotal')),signedReceiptId:d.get('signedReceiptId'),evidence:{reference:d.get('evidenceReference')}},f);}

  return <div className="ops-authority-stack" aria-live="polite">
    <section className="ops-panel ops-wide"><header><div><span>WO-400 · BUS-001–BUS-007</span><h2>Commercial, provisioning and customer authority</h2></div><em data-state={snapshot?'completed':'blocked'}>{snapshot?'connected':'unavailable'}</em></header><p className="ops-authority-message">{message}</p>{totals?<div className="ops-metric-grid"><article><span>Accounts</span><strong>{totals.accounts}</strong></article><article><span>Active tenants</span><strong>{totals.activeAccounts}</strong></article><article><span>Entitlements</span><strong>{totals.activeEntitlements}</strong></article><article><span>Outstanding invoices</span><strong>{totals.outstandingInvoices}</strong></article><article><span>Open support</span><strong>{totals.openSupport}</strong></article><article><span>Blocked reconciliation</span><strong>{totals.blockedReconciliations}</strong></article></div>:null}</section>

    <section className="ops-panel"><header><div><span>CRM → contract</span><h2>Account and opportunity</h2></div></header><form className="ops-admin-form" onSubmit={createAccount}><label>Account name<input required name="accountName" /></label><label>CRM reference<input name="externalCrmId" /></label><label><input name="tenantIsolationVerified" type="checkbox" /> Tenant isolation verified</label><label><input name="billingProfileVerified" type="checkbox" /> Billing profile verified</label><button disabled={busy}>Create account</button></form><form className="ops-admin-form" onSubmit={createOpportunity}><label>Account<select name="accountId"><option value="">Unlinked lead</option>{snapshot?.commercialAccounts.map((row)=><option key={id(row)} value={id(row)}>{label(row,'accountName','externalCrmId')}</option>)}</select></label><label>Stage<select name="stage"><option>lead</option><option>qualified</option><option>proposal</option><option>contracting</option><option>won</option><option>lost</option></select></label><label>Product codes<input required name="productCodes" placeholder="PROVENANCE-T4" /></label><label>Estimated value<input min="0" name="estimatedValue" step="0.01" type="number" /></label><label>Currency<input defaultValue="USD" maxLength={3} name="currency" required /></label><label>Owner<input name="ownerIdentity" required /></label><label>Next action<input name="nextAction" /></label><label>Expected close<input name="expectedCloseAt" type="datetime-local" /></label><button disabled={busy}>Register opportunity</button></form></section>

    <section className="ops-panel"><header><div><span>Contract authority</span><h2>Immutable executed contract</h2></div></header><form className="ops-admin-form" onSubmit={createContract}><label>Account<select required name="accountId"><option value="">Select</option>{snapshot?.commercialAccounts.map((row)=><option key={id(row)} value={id(row)}>{label(row,'accountName','externalCrmId')}</option>)}</select></label><label>Status<select name="status"><option>signed</option><option>active</option></select></label><label>Document SHA-256<input pattern="sha256:[0-9a-f]{64}" required name="documentDigest" /></label><label>Approvers<input required name="approvers" placeholder="legal, customer" /></label><label>Signatures<input required name="signatures" placeholder="sig-1, sig-2" /></label><label>Product codes<input required name="productCodes" /></label><label>Jurisdiction<input required name="jurisdiction" /></label><label>Policy version<input required name="policyVersion" /></label><label>Effective<input required name="effectiveAt" type="datetime-local" /></label><label>Expires<input name="expiresAt" type="datetime-local" /></label><button disabled={busy}>Create contract authority</button></form><form className="ops-admin-form" onSubmit={activateAccount}><label>Account<select required name="accountId">{snapshot?.commercialAccounts.map((row)=><option key={id(row)} value={id(row)}>{label(row,'accountName')}</option>)}</select></label><label>Contract<select required name="contractId">{snapshot?.commercialContracts.map((row)=><option key={id(row)} value={id(row)}>{label(row,'documentDigest','status')}</option>)}</select></label><label>Entitlements<input required name="entitlements" /></label><label>Provisioning receipt<input required name="provisioningReceiptId" /></label><label>Evidence<input required name="evidenceReference" /></label><label><input required name="tenantIsolationVerified" type="checkbox" /> Isolation verified</label><label><input required name="billingProfileVerified" type="checkbox" /> Billing verified</label><button disabled={busy}>Activate tenant entitlements</button></form></section>

    <section className="ops-panel"><header><div><span>Billing authority</span><h2>Invoice, payment and refund</h2></div></header><form className="ops-admin-form" onSubmit={createInvoice}><label>Account<select required name="accountId">{snapshot?.commercialAccounts.map((row)=><option key={id(row)} value={id(row)}>{label(row,'accountName')}</option>)}</select></label><label>Contract<select required name="contractId">{snapshot?.commercialContracts.map((row)=><option key={id(row)} value={id(row)}>{label(row,'documentDigest')}</option>)}</select></label><label>Line code<input required name="lineCode" /></label><label>Quantity<input min="1" name="quantity" required type="number" /></label><label>Unit amount<input min="0" name="unitAmount" required step="0.01" type="number" /></label><label>Tax<input defaultValue="0" min="0" name="taxAmount" step="0.01" type="number" /></label><label>Currency<input defaultValue="USD" maxLength={3} name="currency" required /></label><label>Due<input required name="dueAt" type="datetime-local" /></label><button disabled={busy}>Issue invoice</button></form><form className="ops-admin-form" onSubmit={recordPayment}><label>Invoice<select required name="invoiceId">{snapshot?.invoices.map((row)=><option key={id(row)} value={id(row)}>{label(row,'totalAmount','state')}</option>)}</select></label><label>Amount<input min="0.01" name="amount" required step="0.01" type="number" /></label><label>Currency<input defaultValue="USD" name="currency" required /></label><label>Provider reference<input required name="providerReference" /></label><label>Idempotency key<input required name="idempotencyKey" /></label><button disabled={busy}>Record settled payment</button></form><form className="ops-admin-form" onSubmit={authorizeRefund}><label>Payment<select required name="paymentId">{snapshot?.payments.map((row)=><option key={id(row)} value={id(row)}>{label(row,'providerReference','amount')}</option>)}</select></label><label>Amount<input min="0.01" name="amount" required step="0.01" type="number" /></label><label>Reason<input required name="reason" /></label><label>Independent approvers<input required name="approvers" /></label><label>Approval signatures<input required name="signatures" /></label><label>Authorization receipt<input required name="authorizationReceiptId" /></label><button disabled={busy}>Authorize refund</button></form></section>

    <section className="ops-panel"><header><div><span>Service authority</span><h2>Support and commercial remedy</h2></div></header><form className="ops-admin-form" onSubmit={createSupport}><label>Case type<input required name="caseType" /></label><label>Severity<select name="severity"><option>SEV-1</option><option>SEV-2</option><option>SEV-3</option><option>SEV-4</option></select></label><label>Customer impact<input name="customerImpact" /></label><label>Credential impact<input name="credentialImpact" /></label><label>SLA due<input required name="slaDueAt" type="datetime-local" /></label><label>Escalation path<input required name="escalationPath" /></label><label>Evidence IDs<input required name="evidenceIds" /></label><button disabled={busy}>Open support case</button></form><form className="ops-admin-form" onSubmit={transitionSupport}><label>Case<select required name="caseId">{snapshot?.supportCases.map((row)=><option key={id(row)} value={id(row)}>{label(row,'caseType','state')}</option>)}</select></label><label>To state<select name="toState"><option>triaged</option><option>investigating</option><option>escalated</option><option>resolved</option><option>closed</option><option>reopened</option></select></label><label>Evidence<input required name="evidenceReference" /></label><button disabled={busy}>Commit case transition</button></form><form className="ops-admin-form" onSubmit={remedy}><label>Support case<select required name="supportCaseId">{snapshot?.supportCases.map((row)=><option key={id(row)} value={id(row)}>{label(row,'caseType','state')}</option>)}</select></label><label>Refund<select name="refundId"><option value="">None</option>{snapshot?.refunds.map((row)=><option key={id(row)} value={id(row)}>{label(row,'amount','state')}</option>)}</select></label><label>Remedy type<input required name="remedyType" /></label><label>Financial state<select name="financialState"><option>not-required</option><option>pending</option><option>approved</option><option>completed</option><option>denied</option></select></label><label>Credential action<select name="credentialAction"><option>none</option><option>investigate</option><option>suspend</option><option>reactivate</option><option>revoke</option><option>correct</option></select></label><label>Credential reason<input name="credentialActionReason" /></label><label>Dual-control receipts<input required name="dualControlReceiptIds" /></label><label>Evidence<input required name="evidenceReference" /></label><button disabled={busy}>Authorize coordinated remedy</button></form></section>

    <section className="ops-panel"><header><div><span>Policy and reconciliation</span><h2>Preferences and financial closure</h2></div></header><form className="ops-admin-form" onSubmit={preference}><label>Subject<input required name="subjectReference" /></label><label>Jurisdiction<input required name="jurisdiction" /></label><label>Purpose<input required name="purpose" /></label><label>Channel<input required name="channel" /></label><label>Policy version<input required name="policyVersion" /></label><label>Evidence SHA-256<input pattern="sha256:[0-9a-f]{64}" required name="evidenceDigest" /></label><label>Supersedes<input name="supersedesId" /></label><label><input name="granted" type="checkbox" /> Granted</label><label><input name="withdrawn" type="checkbox" /> Withdrawal record</label><button disabled={busy}>Record preference evidence</button></form><form className="ops-admin-form" onSubmit={reconciliation}><label>Window start<input required name="windowStart" type="datetime-local" /></label><label>Window end<input required name="windowEnd" type="datetime-local" /></label><label>Invoice total<input min="0" name="invoiceTotal" required step="0.01" type="number" /></label><label>Payment total<input min="0" name="paymentTotal" required step="0.01" type="number" /></label><label>Refund total<input defaultValue="0" min="0" name="refundTotal" step="0.01" type="number" /></label><label>Signed receipt<input required name="signedReceiptId" /></label><label>Evidence<input required name="evidenceReference" /></label><button disabled={busy}>Reconcile billing</button></form></section>
  </div>;
}
