'use client';

import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react';
import { authorityFetch } from '@/operations/auth';

type Row = Record<string, unknown> & { id?: string };
type Snapshot = {
  sourceAuthorities: Row[]; claims: Row[]; waivers: Row[]; auditRuns: Row[]; devices: Row[];
  dualControls: Row[]; accessReviews: Row[]; breakGlass: Row[]; keys: Row[]; retention: Row[];
  derivatives: Row[]; appeals: Row[]; calibrations: Row[]; bundles: Row[]; statusLists: Row[];
  batchCommands: Row[]; usage: Row[]; tasks: Row[]; notifications: Row[]; publicClaims: Row[];
  supportCases: Row[]; incidents: Row[]; sloMeasurements: Row[]; integrityFindings: Row[];
};
type Envelope<T> = { data?: T; error?: { code?: string; message?: string } };

async function api<T>(path: string, init?: RequestInit): Promise<T> {
  const response = await authorityFetch(path, { cache: 'no-store', ...init, headers: { 'content-type': 'application/json', ...(init?.headers ?? {}) } });
  const body = await response.json().catch(() => ({})) as Envelope<T>;
  if (!response.ok || !body.data) throw new Error(body.error?.message ?? body.error?.code ?? `AUTHORITY_CONTROL_FAILED_${response.status}`);
  return body.data;
}
function split(value: FormDataEntryValue | null) { return String(value ?? '').split(',').map((item) => item.trim()).filter(Boolean); }
function iso(value: FormDataEntryValue | null) { const raw=String(value ?? ''); return raw ? new Date(raw).toISOString() : ''; }
function digest(seed: string) { return `sha256:${seed.toLowerCase().replace(/[^a-f0-9]/g,'a').padEnd(64,'0').slice(0,64)}`; }
function label(row: Row, ...keys: string[]) { for (const key of keys) if (row[key] != null) return String(row[key]); return String(row.id ?? 'record'); }

export function OperationalGovernancePanel() {
  const [snapshot,setSnapshot]=useState<Snapshot|null>(null);
  const [message,setMessage]=useState('Loading operational authority…');
  const [busy,setBusy]=useState(false);
  const load=useCallback(async()=>{ try { setSnapshot(await api<Snapshot>('/api/v1/authority/operational-controls')); setMessage('Operational authority loaded.'); } catch(error){ setMessage(error instanceof Error?error.message:'Operational authority unavailable.'); } },[]);
  useEffect(()=>{void load();},[load]);
  const totals=useMemo(()=> snapshot ? { claims:snapshot.claims.length, waivers:snapshot.waivers.length, devices:snapshot.devices.length, keys:snapshot.keys.length, openIncidents:snapshot.incidents.filter((item)=>item.state!=='resolved').length, findings:snapshot.integrityFindings.filter((item)=>item.state!=='resolved').length } : null,[snapshot]);
  async function submit(kind:string,payload:Record<string,unknown>,form?:HTMLFormElement){ try{setBusy(true);setMessage(`Committing ${kind}…`);await api(`/api/v1/authority/operational-controls/${kind}`,{method:'POST',body:JSON.stringify(payload)});form?.reset();await load();setMessage(`${kind} committed with server authority.`);}catch(error){setMessage(error instanceof Error?error.message:`${kind} failed closed.`);}finally{setBusy(false);} }
  async function sourceAuthority(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=event.currentTarget,d=new FormData(f),name=String(d.get('name')??'');await submit('source-authorities',{authorityType:d.get('authorityType'),name,sourceUri:d.get('sourceUri'),sourceDigest:d.get('sourceDigest')||digest(name),version:d.get('version'),effectiveAt:iso(d.get('effectiveAt')),expiresAt:iso(d.get('expiresAt'))||null},f);}
  async function runtimeClaim(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=event.currentTarget,d=new FormData(f);await submit('runtime-claims',{sourceAuthorityId:d.get('sourceAuthorityId'),claimKey:d.get('claimKey'),claimClass:d.get('claimClass'),ownerIdentity:d.get('ownerIdentity'),state:d.get('state'),observedAt:iso(d.get('observedAt')),expiresAt:iso(d.get('expiresAt')),payload:{statement:d.get('statement')}},f);}
  async function waiver(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=event.currentTarget,d=new FormData(f);await submit('waivers',{scope:d.get('scope'),risk:d.get('risk'),approverIdentities:split(d.get('approvers')),approvalSignatures:split(d.get('signatures')),compensatingControls:split(d.get('controls')),startsAt:iso(d.get('startsAt')),expiresAt:iso(d.get('expiresAt')),evidence:{reference:d.get('evidence')}},f);}
  async function device(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=event.currentTarget,d=new FormData(f);await submit('devices',{ownerIdentity:d.get('ownerIdentity'),attestationType:d.get('attestationType'),riskState:d.get('riskState'),enrolledAt:iso(d.get('enrolledAt')),lastSeenAt:iso(d.get('lastSeenAt')),attestationEvidence:{reference:d.get('evidence')}},f);}
  async function accessReview(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=event.currentTarget,d=new FormData(f);await submit('access-reviews',{principalIdentity:d.get('principalIdentity'),entitlements:split(d.get('entitlements')),reviewedEntitlements:split(d.get('reviewedEntitlements')),reviewerIdentity:d.get('reviewerIdentity'),reviewerSignature:d.get('reviewerSignature'),dueAt:iso(d.get('dueAt')),completedAt:iso(d.get('completedAt'))||null,blockerOpen:d.get('blockerOpen')==='on'},f);}
  async function breakGlass(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=event.currentTarget,d=new FormData(f);await submit('break-glass',{principalIdentity:d.get('principalIdentity'),reason:d.get('reason'),hardwareMfaVerified:d.get('hardwareMfaVerified')==='on',startsAt:iso(d.get('startsAt')),expiresAt:iso(d.get('expiresAt')),alertReceiptId:d.get('alertReceiptId')},f);}
  async function publicClaim(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=event.currentTarget,d=new FormData(f);await submit('public-claims',{claimKey:d.get('claimKey'),claimText:d.get('claimText'),sourceIds:split(d.get('sourceIds')),approverIds:split(d.get('approverIds')),channels:split(d.get('channels')),effectiveAt:iso(d.get('effectiveAt')),expiresAt:iso(d.get('expiresAt')),state:d.get('state')},f);}
  async function incident(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=event.currentTarget,d=new FormData(f);await submit('incidents',{severity:d.get('severity'),commanderIdentity:d.get('commanderIdentity'),state:d.get('state'),customerImpact:d.get('customerImpact'),timeline:[{at:new Date().toISOString(),event:d.get('timelineEvent')}],evidence:{reference:d.get('evidence')},openedAt:iso(d.get('openedAt'))},f);}
  async function integrity(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=event.currentTarget,d=new FormData(f);await submit('integrity-findings',{findingType:d.get('findingType'),severity:d.get('severity'),subjectReference:d.get('subjectReference'),quarantined:d.get('quarantined')==='on',state:d.get('state'),detectedAt:iso(d.get('detectedAt')),evidence:{reference:d.get('evidence')}},f);}

  async function evidenceAccess(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=event.currentTarget,d=new FormData(f);await submit('evidence-access',{evidenceId:d.get('evidenceId'),principalIdentity:d.get('principalIdentity'),purpose:d.get('purpose'),expiresAt:iso(d.get('expiresAt')),signedAccessReference:d.get('signedAccessReference')},f);}
  async function portableBundle(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=event.currentTarget,d=new FormData(f);await submit('portable-bundles',{credentialId:d.get('credentialId'),credentialVersion:Number(d.get('credentialVersion')),publicKeyReference:d.get('publicKeyReference'),protocolVersion:d.get('protocolVersion'),bundlePayload:{credential:{id:d.get('credentialId'),version:Number(d.get('credentialVersion'))},lifecycleEvents:[{type:'ACTIVE'}],signature:d.get('signature')}},f);}
  async function statusList(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=event.currentTarget,d=new FormData(f);await submit('status-lists',{version:Number(d.get('version')),effectiveAt:iso(d.get('effectiveAt')),keyId:d.get('keyId'),signature:d.get('signature'),snapshot:{revoked:split(d.get('revoked')),suspended:split(d.get('suspended'))}},f);}
  async function consent(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=event.currentTarget,d=new FormData(f);await submit('consents',{subjectReference:d.get('subjectReference'),jurisdiction:d.get('jurisdiction'),purpose:d.get('purpose'),granted:d.get('granted')==='on',policyVersion:d.get('policyVersion'),evidence:{reference:d.get('evidence')}},f);}
  async function taskEvent(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=event.currentTarget,d=new FormData(f);await submit('task-events',{taskId:d.get('taskId'),attemptId:d.get('attemptId'),eventType:d.get('eventType'),payload:{evidence:d.get('evidence'),result:d.get('result')}},f);}
  async function launchCommunication(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=event.currentTarget,d=new FormData(f);await submit('launch-communications',{publicClaimId:d.get('publicClaimId'),channel:d.get('channel'),state:d.get('state'),embargoUntil:iso(d.get('embargoUntil'))||null,externalMessageId:d.get('externalMessageId')||null},f);}
  async function legalLocalization(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=event.currentTarget,d=new FormData(f);await submit('legal-localizations',{documentKey:d.get('documentKey'),locale:d.get('locale'),jurisdiction:d.get('jurisdiction'),version:d.get('version'),governingSourceDigest:d.get('governingSourceDigest'),legalApproverIdentity:d.get('legalApproverIdentity'),approvalSignature:d.get('approvalSignature'),effectiveAt:iso(d.get('effectiveAt')),expiresAt:iso(d.get('expiresAt')),state:'approved',body:{text:d.get('body')}},f);}
  async function trustAssertion(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=event.currentTarget,d=new FormData(f);await submit('trust-assertions',{assertionKey:d.get('assertionKey'),statement:d.get('statement'),evidenceIds:split(d.get('evidenceIds')),ownerIdentity:d.get('ownerIdentity'),observedAt:iso(d.get('observedAt')),expiresAt:iso(d.get('expiresAt')),state:'verified',public:d.get('public')==='on'},f);}

  return <div className="ops-authority-stack" aria-live="polite">
    <section className="ops-panel ops-wide"><header><div><span>R3 · Original 159-gap control plane</span><h2>Operational governance and evidence</h2></div><em data-state={snapshot?'completed':'blocked'}>{snapshot?'connected':'unavailable'}</em></header><p className="ops-authority-message">{message}</p>{totals?<div className="ops-metric-grid"><article><span>Runtime claims</span><strong>{totals.claims}</strong></article><article><span>Waivers</span><strong>{totals.waivers}</strong></article><article><span>Trusted devices</span><strong>{totals.devices}</strong></article><article><span>Authority keys</span><strong>{totals.keys}</strong></article><article><span>Open incidents</span><strong>{totals.openIncidents}</strong></article><article><span>Integrity findings</span><strong>{totals.findings}</strong></article></div>:null}</section>

    <section className="ops-panel"><header><div><span>GOV-001 · GOV-004</span><h2>Source authority and runtime claims</h2></div></header><form className="ops-admin-form" onSubmit={sourceAuthority}><label>Name<input required name="name" /></label><label>Type<select name="authorityType"><option value="governing">Governing</option><option value="runtime">Runtime</option><option value="design">Design</option></select></label><label>Source URI<input required name="sourceUri" /></label><label>Source SHA-256<input name="sourceDigest" placeholder="sha256:…" /></label><label>Version<input required name="version" /></label><label>Effective<input required name="effectiveAt" type="datetime-local" /></label><label>Expires<input name="expiresAt" type="datetime-local" /></label><button disabled={busy}>Register source authority</button></form><form className="ops-admin-form" onSubmit={runtimeClaim}><label>Source authority<select required name="sourceAuthorityId">{snapshot?.sourceAuthorities.map((item)=><option key={String(item.id)} value={String(item.id)}>{label(item,'name','sourceUri')}</option>)}</select></label><label>Claim key<input required name="claimKey" /></label><label>Class<select name="claimClass"><option>VERIFIED_RUNTIME</option><option>GOVERNING</option><option>DESIGN</option><option>TARGET</option><option>ASSUMPTION</option><option>UNVERIFIED</option></select></label><label>Owner<input required name="ownerIdentity" /></label><label>State<select name="state"><option>VERIFIED</option><option>LIVE</option><option>BLOCKED</option></select></label><label>Observed<input required name="observedAt" type="datetime-local" /></label><label>Expires<input required name="expiresAt" type="datetime-local" /></label><label>Statement<input required name="statement" /></label><button disabled={busy}>Commit runtime claim</button></form><ul className="ops-authority-list">{snapshot?.claims.slice(0,8).map((item)=><li key={String(item.id)}><span><strong>{label(item,'claimKey')}</strong><small>{label(item,'claimClass')} · owner {label(item,'ownerIdentity')}</small></span><em data-state={item.state==='LIVE'||item.state==='VERIFIED'?'completed':'blocked'}>{label(item,'state')}</em></li>)}</ul></section>

    <section className="ops-panel"><header><div><span>GOV-006 · IAM-005/011/012</span><h2>Waivers, devices and access authority</h2></div></header><form className="ops-admin-form" onSubmit={waiver}><label>Scope<input required name="scope" /></label><label>Risk<input required name="risk" /></label><label>Approvers<input required name="approvers" placeholder="principal-a, principal-b" /></label><label>Signatures<input required name="signatures" placeholder="sig-a, sig-b" /></label><label>Compensating controls<input required name="controls" /></label><label>Evidence<input required name="evidence" /></label><label>Starts<input required name="startsAt" type="datetime-local" /></label><label>Expires<input required name="expiresAt" type="datetime-local" /></label><button disabled={busy}>Issue expiring waiver</button></form><form className="ops-admin-form" onSubmit={device}><label>Owner<input required name="ownerIdentity" /></label><label>Attestation<select name="attestationType"><option value="webauthn">WebAuthn</option><option value="platform">Platform</option><option value="managed">Managed</option><option value="none">None</option></select></label><label>Risk<select name="riskState"><option value="trusted">Trusted</option><option value="elevated">Elevated</option><option value="revoked">Revoked</option></select></label><label>Evidence<input required name="evidence" /></label><label>Enrolled<input required name="enrolledAt" type="datetime-local" /></label><label>Last seen<input required name="lastSeenAt" type="datetime-local" /></label><button disabled={busy}>Register device</button></form><form className="ops-admin-form" onSubmit={accessReview}><label>Principal<input required name="principalIdentity" /></label><label>Entitlements<input required name="entitlements" /></label><label>Reviewed entitlements<input required name="reviewedEntitlements" /></label><label>Reviewer<input required name="reviewerIdentity" /></label><label>Signature<input required name="reviewerSignature" /></label><label>Due<input required name="dueAt" type="datetime-local" /></label><label>Completed<input name="completedAt" type="datetime-local" /></label><label className="ops-inline-check"><input name="blockerOpen" type="checkbox" />Open blocker if overdue</label><button disabled={busy}>Record access review</button></form><form className="ops-admin-form" onSubmit={breakGlass}><label>Principal<input required name="principalIdentity" /></label><label>Reason<input required name="reason" /></label><label>Alert receipt<input required name="alertReceiptId" /></label><label>Starts<input required name="startsAt" type="datetime-local" /></label><label>Expires<input required name="expiresAt" type="datetime-local" /></label><label className="ops-inline-check"><input name="hardwareMfaVerified" type="checkbox" />Hardware MFA verified</label><button disabled={busy}>Create break-glass lease</button></form></section>

    <section className="ops-panel"><header><div><span>PUB-009 · OBS-007/009</span><h2>Public claims, incidents and integrity</h2></div></header><form className="ops-admin-form" onSubmit={publicClaim}><label>Claim key<input required name="claimKey" /></label><label>Claim text<input required name="claimText" /></label><label>Sources<input required name="sourceIds" /></label><label>Approvers<input required name="approverIds" /></label><label>Channels<input required name="channels" placeholder="web, press, sales" /></label><label>State<select name="state"><option value="approved">Approved</option><option value="published">Published</option><option value="draft">Draft</option></select></label><label>Effective<input required name="effectiveAt" type="datetime-local" /></label><label>Expires<input required name="expiresAt" type="datetime-local" /></label><button disabled={busy}>Commit governed claim</button></form><form className="ops-admin-form" onSubmit={incident}><label>Severity<select name="severity"><option>SEV-1</option><option>SEV-2</option><option>SEV-3</option></select></label><label>Commander<input required name="commanderIdentity" /></label><label>State<select name="state"><option value="open">Open</option><option value="contained">Contained</option><option value="resolved">Resolved</option></select></label><label>Customer impact<input name="customerImpact" /></label><label>Timeline event<input required name="timelineEvent" /></label><label>Evidence<input required name="evidence" /></label><label>Opened<input required name="openedAt" type="datetime-local" /></label><button disabled={busy}>Open incident command</button></form><form className="ops-admin-form" onSubmit={integrity}><label>Finding type<input required name="findingType" /></label><label>Severity<select name="severity"><option>P0</option><option>P1</option><option>P2</option></select></label><label>Subject<input required name="subjectReference" /></label><label>State<select name="state"><option value="open">Open</option><option value="quarantined">Quarantined</option><option value="investigating">Investigating</option><option value="resolved">Resolved</option></select></label><label>Evidence<input required name="evidence" /></label><label>Detected<input required name="detectedAt" type="datetime-local" /></label><label className="ops-inline-check"><input name="quarantined" type="checkbox" />Quarantine affected authority</label><button disabled={busy}>Record integrity finding</button></form></section>

    <section className="ops-panel ops-wide"><header><div><span>EVD-006 · CRE-007/010 · OPS-007 · PUB-005/010 · BUS-008</span><h2>Remaining operational authorities</h2></div></header>
      <form className="ops-admin-form" onSubmit={evidenceAccess}><label>Evidence ID<input required name="evidenceId" /></label><label>Principal<input required name="principalIdentity" /></label><label>Purpose<input required name="purpose" /></label><label>Expires<input required name="expiresAt" type="datetime-local" /></label><label>Signed access reference<input required name="signedAccessReference" /></label><button disabled={busy}>Grant bounded evidence access</button></form>
      <form className="ops-admin-form" onSubmit={portableBundle}><label>Credential ID<input required name="credentialId" /></label><label>Version<input required min="1" name="credentialVersion" type="number" /></label><label>Public key reference<input required name="publicKeyReference" /></label><label>Protocol version<input required name="protocolVersion" /></label><label>Signature<input required name="signature" /></label><button disabled={busy}>Create portable verification bundle</button></form>
      <form className="ops-admin-form" onSubmit={statusList}><label>Version<input required min="1" name="version" type="number" /></label><label>Effective<input required name="effectiveAt" type="datetime-local" /></label><label>Key ID<input required name="keyId" /></label><label>Signature<input required name="signature" /></label><label>Revoked IDs<input name="revoked" /></label><label>Suspended IDs<input name="suspended" /></label><button disabled={busy}>Publish signed status list</button></form>
      <form className="ops-admin-form" onSubmit={consent}><label>Subject<input required name="subjectReference" /></label><label>Jurisdiction<input required name="jurisdiction" /></label><label>Purpose<input required name="purpose" /></label><label>Policy version<input required name="policyVersion" /></label><label>Evidence<input required name="evidence" /></label><label className="ops-inline-check"><input name="granted" type="checkbox" />Consent granted</label><button disabled={busy}>Record consent or withdrawal</button></form>
      <form className="ops-admin-form" onSubmit={taskEvent}><label>Task ID<input required name="taskId" /></label><label>Attempt ID<input required name="attemptId" /></label><label>Event<select name="eventType"><option>created</option><option>started</option><option>tool-call</option><option>tool-result</option><option>continued</option><option>denied</option><option>approved</option><option>completed</option><option>failed</option></select></label><label>Result<input name="result" /></label><label>Evidence<input required name="evidence" /></label><button disabled={busy}>Append task execution event</button></form>
      <form className="ops-admin-form" onSubmit={launchCommunication}><label>Public claim ID<input required name="publicClaimId" /></label><label>Channel<input required name="channel" /></label><label>State<select name="state"><option>approved</option><option>scheduled</option><option>published</option><option>withdrawn</option></select></label><label>Embargo<input name="embargoUntil" type="datetime-local" /></label><label>External message ID<input name="externalMessageId" /></label><button disabled={busy}>Record launch communication</button></form>
      <form className="ops-admin-form" onSubmit={legalLocalization}><label>Document key<input required name="documentKey" /></label><label>Locale<input required name="locale" /></label><label>Jurisdiction<input required name="jurisdiction" /></label><label>Version<input required name="version" /></label><label>Source SHA-256<input required name="governingSourceDigest" /></label><label>Legal approver<input required name="legalApproverIdentity" /></label><label>Approval signature<input required name="approvalSignature" /></label><label>Effective<input required name="effectiveAt" type="datetime-local" /></label><label>Expires<input required name="expiresAt" type="datetime-local" /></label><label>Controlled body<textarea required name="body" /></label><button disabled={busy}>Commit localized legal authority</button></form>
      <form className="ops-admin-form" onSubmit={trustAssertion}><label>Assertion key<input required name="assertionKey" /></label><label>Statement<input required name="statement" /></label><label>Evidence IDs<input required name="evidenceIds" /></label><label>Owner<input required name="ownerIdentity" /></label><label>Observed<input required name="observedAt" type="datetime-local" /></label><label>Expires<input required name="expiresAt" type="datetime-local" /></label><label className="ops-inline-check"><input name="public" type="checkbox" />Publish to trust center</label><button disabled={busy}>Commit evidence-backed trust assertion</button></form>
    </section>
  </div>;
}
