import { signedAuthorityFetch } from '../authority-api/aws-sigv4.ts';

const SUPABASE_URL=Deno.env.get('SUPABASE_URL') ?? '';
const SERVICE_ROLE_KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? '';
const AUTHORITY_API_BASE=(Deno.env.get('PV_AWS_AUTHORITY_API_BASE') ?? '').replace(/\/$/,'');
const WORKER_ID=Deno.env.get('PV_AUDIT_EXPORT_WORKER_ID') ?? `audit-export-worker-${crypto.randomUUID()}`;
const MAX_ROWS=10_000;

type ExportJob={id:string;tenant_id:string;requester_identity:string;scope:Record<string,unknown>;watermark:string;expires_at:string;request_digest:string};
function json(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json'}});}
async function rpc<T>(name:string,body:Record<string,unknown>):Promise<T>{const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:SERVICE_ROLE_KEY,authorization:`Bearer ${SERVICE_ROLE_KEY}`,'content-type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error(`RPC_${name}_${r.status}:${await r.text()}`);return await r.json() as T;}
async function rest<T>(table:string,query:string):Promise<T>{const r=await fetch(`${SUPABASE_URL}/rest/v1/${table}?${query}`,{headers:{apikey:SERVICE_ROLE_KEY,authorization:`Bearer ${SERVICE_ROLE_KEY}`}});if(!r.ok)throw new Error(`REST_${table}_${r.status}:${await r.text()}`);return await r.json() as T;}
async function digest(bytes:Uint8Array){const raw=new Uint8Array(await crypto.subtle.digest('SHA-256',bytes));return {hex:`sha256:${[...raw].map((b)=>b.toString(16).padStart(2,'0')).join('')}`,base64:btoa(String.fromCharCode(...raw))};}
function redact(value:unknown):unknown{if(Array.isArray(value))return value.map(redact);if(value && typeof value==='object'){const out:Record<string,unknown>={};for(const [key,item] of Object.entries(value as Record<string,unknown>)){if(/authorization|secret|token|password|plaintext|encrypted_payload|recipient|contact|email|phone/i.test(key)){out[key]='[REDACTED]';continue;}out[key]=redact(item);}return out;}return value;}
function allowedTables(scope:Record<string,unknown>){const requested=Array.isArray(scope.tables)?scope.tables.map(String):[];const allow=new Set(['pv_authority_events','pv_audit_runs','pv_incidents','pv_integrity_findings','pv_slo_measurements','pv_notification_attempts','pv_audit_export_events']);return requested.filter((table)=>allow.has(table));}
async function build(job:ExportJob){
  const tables=allowedTables(job.scope);if(!tables.length)throw new Error('AUDIT_EXPORT_SCOPE_EMPTY');
  const records:Record<string,unknown>={};
  for(const table of tables){const tenantColumn=['pv_slo_measurements'].includes(table)?null:'tenant_id';const query=new URLSearchParams({select:'*',limit:String(Math.min(MAX_ROWS,Number(job.scope.maxRows ?? 1000)))});if(tenantColumn)query.set(tenantColumn,`eq.${job.tenant_id}`);records[table]=redact(await rest<unknown[]>(table,query.toString()));}
  const payload={schemaVersion:'provenance.audit-export.r3.1',exportId:job.id,tenantId:job.tenant_id,requester:job.requester_identity,watermark:job.watermark,generatedAt:new Date().toISOString(),scope:job.scope,records};
  const bytes=new TextEncoder().encode(JSON.stringify(payload));const sum=await digest(bytes);
  const evidenceId=`audit-export-${job.id}`;const begin=await signedAuthorityFetch({url:`${AUTHORITY_API_BASE}/evidence-custody/v1/uploads/begin`,body:{evidenceId,assetOrLotId:'audit-exports',declaredSha256:sum.hex,byteSize:bytes.byteLength,mimeType:'application/json',contentChecksumBase64:sum.base64},tenantId:job.tenant_id,subject:evidenceId,operation:'evidence.upload.begin',idempotencyKey:`audit-export:${job.id}:begin`,serviceIdentity:'provenance-audit-export-worker'});
  if(!begin.ok)throw new Error(`AUDIT_EXPORT_UPLOAD_BEGIN_${begin.status}`);const authorization=await begin.json() as Record<string,unknown>;const headers=authorization.requiredHeaders as Record<string,string>;const upload=await fetch(String(authorization.uploadUrl),{method:'PUT',headers,body:bytes});if(!upload.ok)throw new Error(`AUDIT_EXPORT_UPLOAD_${upload.status}`);const versionId=upload.headers.get('x-amz-version-id');if(!versionId)throw new Error('AUDIT_EXPORT_VERSION_ID_REQUIRED');
  const finish=await signedAuthorityFetch({url:`${AUTHORITY_API_BASE}/evidence-custody/v1/uploads/finalize`,body:{evidenceId,storageKey:authorization.storageKey,objectVersionId:versionId,declaredSha256:sum.hex,mimeType:'application/json'},tenantId:job.tenant_id,subject:evidenceId,operation:'evidence.upload.finalize',idempotencyKey:`audit-export:${job.id}:finalize`,serviceIdentity:'provenance-audit-export-worker'});
  if(!finish.ok)throw new Error(`AUDIT_EXPORT_FINALIZE_${finish.status}`);const custody=await finish.json() as Record<string,unknown>;
  return rpc('pv_r3_complete_audit_export',{p_export_id:job.id,p_worker_id:WORKER_ID,p_encrypted_reference:`${authorization.storageKey}@${versionId}`,p_export_digest:sum.hex,p_encryption_key_id:String(custody.kmsKeyId ?? 's3-kms-envelope'),p_evidence:{custodyReceipt:custody.receipt,objectVersionId:versionId,byteSize:bytes.byteLength}});
}
Deno.serve(async(request)=>{if(request.method!=='POST')return json({error:'METHOD_NOT_ALLOWED'},405);if(!SUPABASE_URL||!SERVICE_ROLE_KEY||!AUTHORITY_API_BASE)return json({error:'WORKER_CONFIGURATION_INCOMPLETE'},503);try{const jobs=await rpc<ExportJob[]>('pv_r3_claim_audit_exports',{p_worker_id:WORKER_ID,p_limit:5});const results=[];for(const job of jobs){try{results.push(await build(job));}catch(error){results.push({exportId:job.id,error:error instanceof Error?error.message:String(error)});}}return json({workerId:WORKER_ID,claimed:jobs.length,results});}catch(error){return json({error:error instanceof Error?error.message:String(error)},503);}});
